# Generated by Django 3.0.4 on 2020-05-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200507_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
